AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack para crear un bucket S3 para almacenar scripts de configuración para instancias EC2"

Resources:
  ScriptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: equipo3-scripts
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Purpose
          Value: "Almacenar scripts para instancias EC2"

  ScriptsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ScriptsBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${ScriptsBucket}/*"
            Condition:
              StringEquals:
                aws:SourceVpc: !ImportValue equipo3-VPC-ID  # Reemplaza con tu VPC ID

Outputs:
  ScriptsBucketName:
    Description: "Nombre del bucket S3 para scripts"
    Value: !Ref ScriptsBucket
    Export:
      Name: "equipo3-Scripts-Bucket"
