AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack para la creacion de instancias EC2 AZ1"

Parameters:
  KeyName:
    Type: String
    Default: "mensagl"
    Description: "clave para ssh"

Resources:
  EC2ProxyAZ1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue equipo3-SubnetPublic1-ID
      SecurityGroupIds:
        - !ImportValue equipo3-SG-Proxy-AZ1-ID
      PrivateIpAddress: 10.0.1.50
      Tags:
        - Key: Name
          Value: "equipo3-az1-proxy"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install unzip -y
          git clone https://github.com/pablomediavillamesa/mensagl.git
          cp -r mensagl/datos_usuario/AZ1-mensajeria/EC2ProxyAZ1/ /tmp/
          sudo rm -r -f mensagl/
          chmod +x /tmp/EC2ProxyAZ1/haproxy-install.sh /tmp/EC2ProxyAZ1/duckdns-ejabberd-proxy.sh
          sudo /tmp/EC2ProxyAZ1/duckdns-ejabberd-proxy.sh
          sudo /tmp/EC2ProxyAZ1/haproxy-install.sh

  EC2Ejabberd1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue equipo3-SubnetPrivate1-ID
      SecurityGroupIds:
        - !ImportValue equipo3-SG-Ejabberd-ID
      PrivateIpAddress: 10.0.3.10
      Tags:
        - Key: Name
          Value: "equipo3-ejabberd-1"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          wget https://raw.githubusercontent.com/pablomediavillamesa/mensagl/refs/heads/main/datos_usuario/AZ1-mensajeria/EC2Ejabberd1/instalar_ejabberd.sh -O instalar_ejabberd.sh
          chmod +x instalar_ejabberd.sh 
          sudo /instalar_ejabberd.sh
          echo "instalacion de ejabberd completada con exito"


  EC2PostgreSQL1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04b4f1a9cf54c11d0 # Ubuntu Server 24.04
      KeyName: !Ref KeyName
      SubnetId: !ImportValue equipo3-SubnetPrivate1-ID
      SecurityGroupIds:
        - !ImportValue equipo3-SG-PostgreSQL-ID
      PrivateIpAddress: 10.0.3.100
      Tags:
        - Key: Name
          Value: "equipo3-az1-postgresql-1"