AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stack para configurar una base de datos RDS conectada a equipo3-az2-rds.'

Resources:
  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: '8.0'
      MasterUsername: admin
      MasterUserPassword: Password1234
      DBName: equipo3Wordpress
      VPCSecurityGroups:
        - !ImportValue equipo3-SG-RDS-ID
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
      BackupRetentionPeriod: 7
      PubliclyAccessible: false
      MultiAZ: false

  RDSSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'Subnets for the RDS database.'
      SubnetIds:
        - !ImportValue equipo3-SubnetPrivate1-ID
        - !ImportValue equipo3-SubnetPrivate2-ID

Outputs:
  RDSDatabaseEndpoint:
    Description: "Endpoint de la base de datos RDS"
    Value: !Ref RDSInstance
    Export:
      Name: "equipo3-RDS-Endpoint"
